### PR TITLE
Remove some sniffs

### PR DESCRIPTION
**Pull request by xxsimoxx**
Remove some sniffs that are about code styling.

- `Squiz.PHP.EmbeddedPhp.SpacingBeforeClose`
- `PSR2.Files.ClosingTag.NotAllowed`
- `Generic.ControlStructures.InlineControlStructure.NotAllowed`
- `Generic.PHP.LowerCaseKeyword.Found`

### CODE REVIEW

**Review by viktorix — APPROVED** [review]
Makes sense.

**Comment by joyously** [comment]
Is this one `PSR2.Files.ClosingTag.NotAllowed` about the `?>` tag at the bottom of a file? I think that is definitely needed.

I think that `Generic.PHP.LowerCaseKeyword.Found` should be kept also.

**Comment by viktorix** [comment]
I guess you want to enforce leaving closing tags out to avoid the possibility of sending anything, such as whitespaces, to the browser? I can see that as a possible reason to leave this in, in case developers aren't paying attention. @xxsimoxx what do you think?

But what about the PHP keywords being lowercase? They are case-insensitive, so it is a styling choice. For example, [CodeIgniter](https://codeigniter.com/userguide3/general/styleguide.html#true-false-and-null) requires TRUE, FALSE, and NULL to be upper case.

**Comment by xxsimoxx** [comment]
I've interpreted `PSR2.Files.ClosingTag.NotAllowed` as a way not to send out garbage too. For me this is not a security matter so I deleted it, but can bring it back.
About `Generic.PHP.LowerCaseKeyword.Found` I can't see nothing but a style issue, but if there are other reason to leave it I've no problem with that.

**Pull request merged**
